from __future__ import annotations

import filecmp
import json
import os
import shutil
import stat
import subprocess
from os import environ
from typing import TYPE_CHECKING, Any, Final

try:
    import evdev
except Exception:
    evdev = None

from ... import Command
from ...batoceraPaths import BIOS, CACHE, CONFIGS, ROMS, SAVES, configure_emulator, mkdir_if_not_exists
from ...controller import generate_sdl_game_controller_config
from ..Generator import Generator

if TYPE_CHECKING:
    from pathlib import Path

    from ...types import HotkeysContext

ryujinxConf: Final = CONFIGS / "Ryujinx"
ryujinxConfFile: Final = ryujinxConf / "Config.json"
switchBios: Final = BIOS / "switch"
switchKeysDir: Final = switchBios / "keys"
switchNandDir: Final = switchBios / "nand"
ryujinxKeys: Final = switchBios / "prod.keys"
ryujinxExec: Final = ryujinxConf / "ryujinx"

# UCLAMP values (out of 1024)
# 819 = ~80% utilization floor, forces scheduler to use big cores
UCLAMP_MIN = 819
UCLAMP_MAX = 1024

ryujinxCtrl: dict[str, Any] = {
        "left_joycon_stick": {
        "joystick": "Left",
        "invert_stick_x": False,
        "invert_stick_y": False,
        "rotate90_cw": False,
        "stick_button": "LeftStick"
      },
      "right_joycon_stick": {
        "joystick": "Right",
        "invert_stick_x": False,
        "invert_stick_y": False,
        "rotate90_cw": False,
        "stick_button": "RightStick"
      },
      "deadzone_left": 0,
      "deadzone_right": 0,
      "range_left": 1,
      "range_right": 1,
      "trigger_threshold": 0,
      "motion": {
        "motion_backend": "GamepadDriver",
        "sensitivity": 100,
        "gyro_deadzone": 1,
        "enable_motion": True
      },
      "rumble": {
        "strong_rumble": 8,
        "weak_rumble": 2,
        "enable_rumble": True
      },
      "left_joycon": {
        "button_minus": "Minus",
        "button_l": "LeftShoulder",
        "button_zl": "LeftTrigger",
        "button_sl": "Unbound",
        "button_sr": "Unbound",
        "dpad_up": "DpadUp",
        "dpad_down": "DpadDown",
        "dpad_left": "DpadLeft",
        "dpad_right": "DpadRight"
      },
      "right_joycon": {
        "button_plus": "Plus",
        "button_r": "RightShoulder",
        "button_zr": "RightTrigger",
        "button_sl": "Unbound",
        "button_sr": "Unbound",
        "button_x": "Y",
        "button_b": "A",
        "button_y": "X",
        "button_a": "B"
    },
    "version": 1,
    "backend": "GamepadSDL2",
}

class RyujinxGenerator(Generator):

    def getHotkeysContext(self) -> HotkeysContext:
        return {
            "name": "ryujinx",
            "keys": {"exit": "batocera-es-swissknife --emukill 0.5"}
        }

    def generate(self, system, rom, playersControllers, metadata, guns, wheels, gameResolution):
        mkdir_if_not_exists(ryujinxConf / "system")
        mkdir_if_not_exists(switchBios)
        mkdir_if_not_exists(switchKeysDir)

        # Copy file & make executable (workaround)
        files_to_copy = [
            ("/usr/ryujinx/Ryujinx", ryujinxExec, 0o0775),
            ("/usr/ryujinx/libSkiaSharp.so", ryujinxConf / "libSkiaSharp.so", 0o0644),
            ("/usr/ryujinx/libHarfBuzzSharp.so", ryujinxConf / "libHarfBuzzSharp.so", 0o0644)
        ]

        for src, dest, mode in files_to_copy:
            if not dest.exists() or not filecmp.cmp(src, dest):
                shutil.copyfile(src, dest)
                dest.chmod(mode)

        # Prefer shared Switch BIOS paths for keys/NAND and link into Ryujinx layout.
        _link_dir_into_expected(switchNandDir, ryujinxConf / "bis")
        _bootstrap_firmware_registered_from_flat_nand(switchNandDir, ryujinxConf / "bis")
        prod_key_source = _pick_existing_path(
            switchKeysDir / "prod.keys",
            switchBios / "prod.keys",
        )
        title_key_source = _pick_existing_path(
            switchKeysDir / "title.keys",
            switchKeysDir / "title.keys_autogenerated",
            switchBios / "title.keys",
            switchBios / "title.keys_autogenerated",
        )
        if prod_key_source is not None:
            _link_key_file_into_expected(prod_key_source, ryujinxConf / "system" / "prod.keys")
        if title_key_source is not None:
            _link_key_file_into_expected(title_key_source, ryujinxConf / "system" / "title.keys")

        # Backward compatibility with legacy /userdata/bios/switch/prod.keys
        if not (ryujinxConf / "system" / "prod.keys").exists() and ryujinxKeys.exists():
            shutil.copyfile(ryujinxKeys, ryujinxConf / "system" / "prod.keys")

        # [Configuration]
        mkdir_if_not_exists(ryujinxConfFile.parent)
        try:
            conf = json.load(ryujinxConfFile.open("r"))
        except Exception:
            conf = {}

        # Set defaults
        conf.pop("hide_cursor_on_idle", None)
        conf["enable_discord_integration"] = False
        conf["check_updates_on_start"] = False
        conf["show_confirm_exit"] = False
        conf["hide_cursor"] = 1
        conf["game_dirs"] = [str(ROMS / "switch")]
        conf["start_fullscreen"] = True
        conf["show_title_bar"] = system.config.get_bool("ryujinx_show_title_bar", False)
        conf["remember_window_state"] = False
        conf["use_input_global_config"] = False
        conf["start_no_ui"] = system.config.get_bool("ryujinx_no_ui", not configure_emulator(rom))
        conf["audio_volume"] = 1
        
        # set ryujinx app language
        conf["language_code"] = getLangFromEnvironment()

        # Console language
        conf["system_language"] = system.config.get("ryujinx_language", "AmericanEnglish")
        
        # Console region
        conf["system_region"] = system.config.get("ryujinx_region", "USA")

        # Timezone offset
        conf["system_time_zone"] = "UTC"
        conf["system_time_offset"] = system.config.get_int("ryujinx_timeoffset", 0)

        # Docked mode
        conf["docked_mode"] = system.config.get_bool("ryujinx_docked_mode", True)

        # ==================== GRAPHICS ====================
        # Graphics backend
        graphics_backend = system.config.get("ryujinx_api", "Vulkan")
        conf["graphics_backend"] = graphics_backend
        
        # Internal resolution scale
        res_scale = system.config.get("ryujinx_scale", "1")
        # Handle float values like 0.5, 0.8
        try:
            conf["res_scale"] = float(res_scale) if '.' in str(res_scale) else int(res_scale)
        except (ValueError, TypeError):
            conf["res_scale"] = 1
        
        # Aspect ratio
        conf["aspect_ratio"] = system.config.get("ryujinx_ratio", "Fixed16x9")
        
        # Anisotropic filtering
        conf["max_anisotropy"] = system.config.get_int("ryujinx_filtering", -1)
        
        # VSync mode
        vsync_mode = system.config.get_int("ryujinx_vsync", 0)
        conf["enable_vsync"] = vsync_mode != 0
        conf["vsync_mode"] = vsync_mode
        
        # Backend threading + shader cache.
        # Vulkan can use a combined ES toggle for async GPU/shader behavior.
        async_gpu_shader = system.config.get("ryujinx_async_gpu_shader", "")
        if graphics_backend == "Vulkan" and async_gpu_shader in ("true", "false", "1", "0"):
            enable_async_gpu_shader = async_gpu_shader in ("true", "1")
            conf["backend_threading"] = "Auto" if enable_async_gpu_shader else "Off"
            conf["enable_shader_cache"] = enable_async_gpu_shader
        else:
            if system.config.get_bool("ryujinx_backend_threading", True):
                conf["backend_threading"] = "Auto"
            else:
                conf["backend_threading"] = "Off"
            conf["enable_shader_cache"] = system.config.get_bool("ryujinx_shader_cache", True)
        
        # Scaling filter
        conf["scaling_filter"] = system.config.get("ryujinx_scaling_filter", "Bilinear")
        
        # Anti-aliasing
        conf["anti_aliasing"] = system.config.get("ryujinx_antialiasing", "None")
        
        # Texture recompression
        conf["enable_texture_recompression"] = system.config.get_bool("ryujinx_texture_recompression", False)

        # ==================== EMULATION ====================
        # Enable PPTC (Profiled Persistent Translation Cache)
        conf["enable_ptc"] = system.config.get_bool("ryujinx_enable_ptc", True)
        
        # FS integrity checks
        conf["enable_fs_integrity_checks"] = system.config.get_bool("ryujinx_fs_integrity", True)
        
        # Memory manager mode
        conf["memory_manager_mode"] = system.config.get("ryujinx_memory_manager", "HostMappedUnsafe")
        
        # Ignore missing services
        conf["ignore_missing_services"] = system.config.get_bool("ryujinx_ignore_missing", False)

        # ==================== AUDIO ====================
        # Audio backend
        conf["audio_backend"] = system.config.get("ryujinx_audio_backend", "OpenAl")

        # ==================== NETWORK ====================
        # Multiplayer/LAN mode
        network_mode = system.config.get("ryujinx_network", "no")
        if network_mode == "local":
            conf["multiplayer_mode"] = 1
            conf["multiplayer_lan_interface_id"] = "0"
        elif network_mode == "internet":
            conf["multiplayer_mode"] = 2
        else:
            conf["multiplayer_mode"] = 0

        conf["input_config"] = []

        # write / update the config file
        js_out = json.dumps(conf, indent=2)
        with ryujinxConfFile.open("w") as jout:
            jout.write(js_out)

        # Now add Controllers
        for nplayer, pad in enumerate(playersControllers[:8], start=1):
            ctrlConf = ryujinxCtrl.copy()
            # Deep copy the nested dicts
            ctrlConf["left_joycon_stick"] = ryujinxCtrl["left_joycon_stick"].copy()
            ctrlConf["right_joycon_stick"] = ryujinxCtrl["right_joycon_stick"].copy()
            ctrlConf["motion"] = ryujinxCtrl["motion"].copy()
            ctrlConf["rumble"] = ryujinxCtrl["rumble"].copy()
            ctrlConf["left_joycon"] = ryujinxCtrl["left_joycon"].copy()
            ctrlConf["right_joycon"] = ryujinxCtrl["right_joycon"].copy()

            # Shared per-player settings
            padtype_key = f"ryujinx_padtype{nplayer}"
            ctrlConf["controller_type"] = system.config.get(padtype_key, "ProController")
            ctrlConf["player_index"] = f"Player{nplayer}"
            ctrlConf["deadzone_left"] = system.config.get_float("ryujinx_deadzone_left", 0)
            ctrlConf["deadzone_right"] = system.config.get_float("ryujinx_deadzone_right", 0)
            ctrlConf["rumble"]["enable_rumble"] = system.config.get_bool("ryujinx_rumble", True)
            ctrlConf["motion"]["enable_motion"] = system.config.get_bool("ryujinx_motion", True)

            if system.config.get_bool("ryujinx_gamepadbuttons"):
                ctrlConf["right_joycon"]["button_a"] = "A"
                ctrlConf["right_joycon"]["button_b"] = "B"
                ctrlConf["right_joycon"]["button_x"] = "X"
                ctrlConf["right_joycon"]["button_y"] = "Y"

            ctrlConf["id"] = _build_ryujinx_controller_id(pad, nplayer)
            ctrlConf["name"] = pad.real_name or pad.name
            writeControllerIntoJson(ctrlConf)

        # ---- Ensure vm.max_map_count is high enough for Ryujinx ----
        VMREQ = 1048576  # future-proof (1M)
        try:
            current_vm = int(subprocess.check_output(
                ["sysctl", "-n", "vm.max_map_count"]
            ).decode().strip())

            if current_vm < VMREQ:
                subprocess.run(
                    ["sysctl", "-w", f"vm.max_map_count={VMREQ}"],
                    check=False
                )
        except Exception:
            pass

        # ---- UCLAMP performance tuning for big.LITTLE ----
        use_uclamp = system.config.get_bool("perf_uclamp", True)
        uclamp_min = system.config.get_int("perf_uclamp_min", UCLAMP_MIN)

        launch_args: list[str] = []
        if not configure_emulator(rom):
            if conf.get("start_fullscreen", True):
                launch_args.append("--fullscreen")
            if conf.get("start_no_ui", True):
                launch_args.append("--no-gui")

        if configure_emulator(rom):
            base_command = [ryujinxExec]
        else:
            base_command = [ryujinxExec, *launch_args, rom]

        wrapper_path = ryujinxConf / "ryujinx-launch.sh"
        RyujinxGenerator._write_runtime_wrapper(
            wrapper_path,
            str(ryujinxExec),
            use_uclamp=use_uclamp,
            uclamp_min=uclamp_min,
            uclamp_max=UCLAMP_MAX,
            force_fullscreen_toggle=bool(conf.get("start_fullscreen", True) and not configure_emulator(rom)),
        )
        if configure_emulator(rom):
            commandArray = [str(wrapper_path)]
        else:
            commandArray = [str(wrapper_path), *launch_args, rom]

        xdg_open_wrapper = ryujinxConf / "xdg-open"
        RyujinxGenerator._write_xdg_open_wrapper(xdg_open_wrapper)
        xdg_path = f"{ryujinxConf}:/sbin:/usr/sbin:/bin:/usr/bin"

        return Command.Command(
            array=commandArray,
            env={"XDG_CONFIG_HOME": CONFIGS,
            "XDG_DATA_HOME": SAVES / "switch",
            "XDG_CACHE_HOME": CACHE,
            "XDG_MENU_PREFIX": "batocera-",
            "XDG_CONFIG_DIRS": "/etc/xdg",
            "XDG_CURRENT_DESKTOP": "XFCE",
            "DESKTOP_SESSION": "XFCE",
            "PATH": xdg_path,
            "SDL_GAMECONTROLLERCONFIG": generate_sdl_game_controller_config(playersControllers),
            "SDL_JOYSTICK_HIDAPI": "0"
            }
        )

    @staticmethod
    def _write_runtime_wrapper(
        wrapper_path: Path,
        executable: str,
        *,
        use_uclamp: bool,
        uclamp_min: int,
        uclamp_max: int,
        force_fullscreen_toggle: bool,
    ):
        """
        Creates a wrapper script that can apply UCLAMP values and send a delayed
        fullscreen toggle when Ryujinx ignores its own start_fullscreen settings.
        """
        script_content = f'''#!/bin/bash
# Auto-generated runtime wrapper for Ryujinx

EXEC="{executable}"
USE_UCLAMP={1 if use_uclamp else 0}
UCLAMP_MIN={uclamp_min}
UCLAMP_MAX={uclamp_max}
FORCE_FULLSCREEN_TOGGLE={1 if force_fullscreen_toggle else 0}

# Launch emulator in background
"$EXEC" "$@" &
EMU_PID=$!

# Apply UCLAMP settings to main process and all threads
apply_uclamp() {{
    local pid=$1
    if [ -d "/proc/$pid" ]; then
        # Main process
        [ -e /proc/$pid/sched_util_min ] && echo $UCLAMP_MIN > /proc/$pid/sched_util_min
        [ -e /proc/$pid/sched_util_max ] && echo $UCLAMP_MAX > /proc/$pid/sched_util_max
        
        # All threads
        for tid in /proc/$pid/task/*/; do
            tid=$(basename "$tid")
            [ -e /proc/$pid/task/$tid/sched_util_min ] && echo $UCLAMP_MIN > /proc/$pid/task/$tid/sched_util_min
            [ -e /proc/$pid/task/$tid/sched_util_max ] && echo $UCLAMP_MAX > /proc/$pid/task/$tid/sched_util_max
        done
    fi
}}

if [ "$USE_UCLAMP" = "1" ]; then
    sleep 0.2
    apply_uclamp $EMU_PID
fi

if [ "$FORCE_FULLSCREEN_TOGGLE" = "1" ]; then
    (
        sleep 4
        if command -v xdotool >/dev/null 2>&1 && [ -n "${{DISPLAY:-}}" ]; then
            xdotool search --sync --onlyvisible --pid "$EMU_PID" key --window %@ F11 >/dev/null 2>&1 || true
        elif command -v wtype >/dev/null 2>&1 && [ -n "${{WAYLAND_DISPLAY:-}}" ]; then
            wtype -k F11 >/dev/null 2>&1 || true
        fi
    ) &
    FULLSCREEN_PID=$!
else
    FULLSCREEN_PID=""
fi

if [ "$USE_UCLAMP" = "1" ]; then
    (
        while kill -0 $EMU_PID 2>/dev/null; do
            sleep 2
            apply_uclamp $EMU_PID
        done
    ) &
    MONITOR_PID=$!
else
    MONITOR_PID=""
fi

# Wait for emulator to exit
wait $EMU_PID
EXIT_CODE=$?

# Cleanup monitor
[ -n "$MONITOR_PID" ] && kill $MONITOR_PID 2>/dev/null || true
[ -n "$FULLSCREEN_PID" ] && kill $FULLSCREEN_PID 2>/dev/null || true

exit $EXIT_CODE
'''
        with open(wrapper_path, 'w') as f:
            f.write(script_content)
        
        os.chmod(wrapper_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

    @staticmethod
    def _write_xdg_open_wrapper(wrapper_path: Path):
        """
        Ryujinx "Open Folder" uses xdg-open.
        On Batocera, gio can fail to resolve inode/directory handlers.
        This wrapper forces directory targets through filemanagerlauncher.
        """
        script_content = '''#!/bin/sh
set -eu

real_xdg_open="/usr/bin/xdg-open"
target="${1:-}"

if [ -z "$target" ]; then
    exec "$real_xdg_open" "$@"
fi

case "$target" in
    file://*)
        path="${target#file://}"
        ;;
    *)
        path="$target"
        ;;
esac

if [ -d "$path" ]; then
    if command -v filemanagerlauncher >/dev/null 2>&1; then
        exec filemanagerlauncher "$path"
    fi
    if command -v pcmanfm >/dev/null 2>&1; then
        exec pcmanfm "$path"
    fi
fi

exec "$real_xdg_open" "$@"
'''
        with open(wrapper_path, 'w') as f:
            f.write(script_content)

        os.chmod(wrapper_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)


def writeControllerIntoJson(new_controller: dict[str, Any], filename: Path = ryujinxConfFile):
    with filename.open('r+') as file:
        file_data = json.load(file)
        file_data.setdefault("input_config", [])
        file_data["input_config"].append(new_controller)
        file.seek(0)
        json.dump(file_data, file, indent=2)
        file.truncate()

def getLangFromEnvironment():
    lang = environ['LANG'][:5]
    availableLanguages = {"ja_JP", "en_US", "de_DE", "fr_FR", "es_ES", "it_IT", "nl_NL", "zh_CN", "zh_TW", "ko_KR"}
    if lang in availableLanguages:
        return lang
    return "en_US"


def _build_ryujinx_controller_id(pad, nplayer):
    if evdev is None:
        return str(nplayer - 1)

    try:
        devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
    except Exception:
        return str(nplayer - 1)

    for dev in devices:
        try:
            if dev.path != pad.device_path:
                continue

            bustype = f"{dev.info.bustype:08x}"
            vendor = f"{dev.info.vendor:04x}"
            product = f"{dev.info.product:04x}"
            version = f"{dev.info.version:04x}"
            product = product[2:] + product[:2]
            version = version[2:] + version[:2]
            pad_index = getattr(pad, "index", nplayer - 1)
            return f"{pad_index}-{bustype}-{vendor}-0000-{product}-0000{version}0000"
        except Exception:
            continue

    return str(nplayer - 1)


def _link_dir_into_expected(source_dir, expected_dir):
    if not source_dir.exists():
        return

    if expected_dir.is_symlink():
        try:
            if expected_dir.resolve() == source_dir.resolve():
                return
        except FileNotFoundError:
            pass
        expected_dir.unlink(missing_ok=True)
        expected_dir.symlink_to(source_dir, target_is_directory=True)
        return

    if expected_dir.exists():
        return

    expected_dir.parent.mkdir(parents=True, exist_ok=True)
    expected_dir.symlink_to(source_dir, target_is_directory=True)


def _link_key_file_into_expected(source_file, expected_file):
    if not source_file.exists():
        return

    if expected_file.is_symlink():
        try:
            if expected_file.resolve() == source_file.resolve():
                return
        except FileNotFoundError:
            pass
        expected_file.unlink(missing_ok=True)
        expected_file.symlink_to(source_file)
        return

    if expected_file.exists():
        return

    expected_file.parent.mkdir(parents=True, exist_ok=True)
    expected_file.symlink_to(source_file)


def _pick_existing_path(*candidates):
    for path in candidates:
        if path.exists():
            return path
    return None


def _bootstrap_firmware_registered_from_flat_nand(nand_root, bis_root):
    """
    Some firmware dumps are flattened with *.nca files at NAND root.
    Ryujinx expects firmware content under bis/system/Contents/registered.
    If registered is empty, symlink loose NCAs into that folder.
    """
    if not nand_root.exists():
        return

    registered = bis_root / "system" / "Contents" / "registered"
    registered.mkdir(parents=True, exist_ok=True)

    try:
        if any(registered.iterdir()):
            return
    except OSError:
        return

    loose_ncas = sorted(p for p in nand_root.glob("*.nca") if p.is_file())
    if not loose_ncas:
        return

    for nca in loose_ncas:
        target = registered / nca.name

        # Replace symlinks with regular files/hardlinks for tools that skip symlink entries.
        if target.is_symlink():
            target.unlink(missing_ok=True)
        elif target.exists():
            continue

        try:
            os.link(nca, target)
        except OSError:
            # Cross-device fallback: copy as a normal file.
            shutil.copy2(nca, target)
