# Add here your local repos and config parameters
#
# Example private repo on a VPS:
# [myrepo]
# SigLevel = Optional TrustAll
# Server = https://repo.example.com/$arch
#
# Example local filesystem repo:
# [localrepo]
# SigLevel = Optional TrustAll
# Server = file:///userdata/system/pacman/repo
