################################################################################
#
# nvtop
#
################################################################################

NVTOP_VERSION = 3.3.2
NVTOP_SITE = $(call github,Syllo,nvtop,$(NVTOP_VERSION))
NVTOP_LICENSE = GPL-3.0+
NVTOP_LICENSE_FILES = COPYING

NVTOP_DEPENDENCIES = host-pkgconf libdrm ncurses udev

NVTOP_CONF_OPTS += \
	-DBUILD_TESTING=OFF \
	-DUSE_LIBUDEV_OVER_LIBSYSTEMD=ON \
	-DNVIDIA_SUPPORT=OFF \
	-DAPPLE_SUPPORT=OFF \
	-DASCEND_SUPPORT=OFF \
	-DTPU_SUPPORT=OFF \
	-DROCKCHIP_SUPPORT=OFF \
	-DMETAX_SUPPORT=OFF \
	-DENFLAME_SUPPORT=OFF \
	-DPANTHOR_SUPPORT=OFF

ifeq ($(BR2_PACKAGE_LIBDRM_AMDGPU),y)
NVTOP_CONF_OPTS += -DAMDGPU_SUPPORT=ON
else
NVTOP_CONF_OPTS += -DAMDGPU_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBDRM_INTEL),y)
NVTOP_CONF_OPTS += -DINTEL_SUPPORT=ON
else
NVTOP_CONF_OPTS += -DINTEL_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBDRM_FREEDRENO),y)
NVTOP_CONF_OPTS += -DMSM_SUPPORT=ON
else
NVTOP_CONF_OPTS += -DMSM_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBDRM_VC4),y)
NVTOP_CONF_OPTS += -DV3D_SUPPORT=ON
else
NVTOP_CONF_OPTS += -DV3D_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBDRM_ETNAVIV),y)
NVTOP_CONF_OPTS += -DPANFROST_SUPPORT=ON
else
NVTOP_CONF_OPTS += -DPANFROST_SUPPORT=OFF
endif

$(eval $(cmake-package))
